---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kobo.fullname" . }}-kobocat
  labels:
    {{- include "kobo.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "-1"
data:
  KOBOCAT_MONGO_NAME: {{ required "mongoName is required" .Values.kobotoolbox.mongoName }}
  DJANGO_LANGUAGE_CODES: {{ quote .Values.kobotoolbox.djangoLanguageCodes }}
{{- if .Values.kpi.ingress.enabled }}
  KOBOFORM_URL: {{ include "kobo.kpiUrl" . | quote }}
{{- end }}
  KOBOFORM_INTERNAL_URL: http://{{ include "kobo.fullname" . }}-kpi
{{- if .Values.kobocat.ingress.enabled }}
  KOBOCAT_URL: {{ include "kobo.kobocatUrl" . | quote }}
{{- end }}
  KOBOCAT_INTERNAL_URL: http://{{ include "kobo.fullname" . }}-kobocat
  SERVICE_ACCOUNT_WHITELISTED_HOSTS: {{ include "kobo.fullname" . }}-kobocat
{{- if .Values.enketo.ingress.enabled }}
  ENKETO_URL: {{ include "kobo.enketoUrl" . | quote }}
{{- end }}
{{- if not .Values.kpi.env.normal.DEFAULT_FROM_EMAIL }}
  DEFAULT_FROM_EMAIL: "support@kobotoolbox.org"
{{- end }}
{{- if not .Values.kpi.env.normal.ENKETO_EXPRESS_PUBLIC_SUBDOMAIN }}
  ENKETO_EXPRESS_PUBLIC_SUBDOMAIN: "ee"
{{- end }}
{{- if not .Values.kpi.env.normal.KOBOCAT_PUBLIC_SUBDOMAIN }}
  KOBOCAT_PUBLIC_SUBDOMAIN: "kc"
{{- end }}
{{- if not .Values.kpi.env.normal.KOBOFORM_PUBLIC_SUBDOMAIN }}
  KOBOFORM_PUBLIC_SUBDOMAIN: "kf"
{{- end }}
{{- if not .Values.kpi.env.normal.PUBLIC_REQUEST_SCHEME }}
  PUBLIC_REQUEST_SCHEME: "https"
{{- end }}
{{- if not .Values.kpi.env.normal.SECURE_HSTS_SECONDS }}
  SECURE_HSTS_SECONDS: "3000"
{{- end }}
{{- range $k, $v := .Values.kobocat.env.normal }}
  {{ $k }}: {{ $v | quote }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kobo.fullname" . }}-kobocat-scripts
  labels:
    {{- include "kobo.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/kobocat/run-uwsgi.sh").AsConfig | indent 2}}
{{ (.Files.Glob "files/kobocat/init.sh").AsConfig | indent 2}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kobo.fullname" . }}-nginx-kobocat-conf
  labels:
    component: kobocat
    {{- include "kobo.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/kobocat/nginx.conf").AsConfig | indent 2 }}
