---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kobo.fullname" . }}-kobocat
  labels:
    {{- include "kobo.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "-1"
data:
  KOBOCAT_MONGO_HOST: {{ required "mongoHost is required" .Values.kobotoolbox.mongoHost }}
  KOBOCAT_MONGO_NAME: {{ required "mongoName is required" .Values.kobotoolbox.mongoName }}
  KOBOCAT_MONGO_USER: {{ required "mongoUser is required" .Values.kobotoolbox.mongoUser }}
{{- if .Values.kobocat.ingress.enabled }}
  KOBOCAT_URL: {{ include "kobo.kobocatUrl" . | quote }}
{{- end }}
{{- range $k, $v := .Values.kobocat.env.normal }}
  {{ $k }}: {{ $v | quote }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kobocat-scripts
  labels:
    {{- include "kobo.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/kobocat/run-uwsgi.sh").AsConfig | indent 2}}
{{ (.Files.Glob "files/kobocat/init.sh").AsConfig | indent 2}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-kobocat-conf
  labels:
    component: kobocat
    {{- include "kobo.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/kobocat/nginx.conf").AsConfig | indent 2 }}