apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kobo.fullname" . }}-kobocat-beat
  labels:
    app.kubernetes.io/component: kobocat-beat
    {{- include "kobo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kobocat-beat
      {{- include "kobo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/kobocat/secrets.yaml") . | sha256sum }}
        checksum/configmap: {{ include (print $.Template.BasePath "/kobocat/configmap.yaml") . | sha256sum }}
        tag: "{{ .Values.kobocat.image.tag }}"
      labels:
        app.kubernetes.io/component: kobocat-beat
        {{- include "kobo.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.kobocat.image.repository }}:{{ .Values.kobocat.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.kobocat.image.pullPolicy }}
          resources:
            limits:
              cpu: 50m
              memory: 256Mi
            requests:
              cpu: 1m
              memory: 32Mi
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- if .Values.postgresql.enabled }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "kobo.postgresql.fullname" .) .Values.postgresql.auth.existingSecret }}
                  key: postgres-password
            - name: DATABASE_URL
              value: postgis://postgres:$(POSTGRES_PASSWORD)@{{ (include "kobo.postgresql.fullname" .) }}:5432/postgres
            {{- end }}
            {{- if .Values.mongodb.enabled }}
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "kobo.mongodb.fullname" .) .Values.mongodb.auth.existingSecret }}
                  key: mongodb-passwords
            - name: MONGO_DB_URL
              value: mongodb://root:$(MONGODB_PASSWORD)@{{ (include "kobo.mongodb.fullname" .) }}:27017
            {{- end }}
            {{- if .Values.redis.enabled }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "kobo.redis.fullname" .) .Values.redis.auth.existingSecret }}
                  key: redis-password
            - name: REDIS_SESSION_URL
              value: redis://:$(REDIS_PASSWORD)@{{ (include "kobo.redis.fullname" .) }}-master:6379/1
            - name: SERVICE_ACCOUNT_BACKEND_URL
              value: redis://:$(REDIS_PASSWORD)@{{ (include "kobo.redis.fullname" .) }}-master:6379/6
            - name: KOBOCAT_BROKER_URL
              value: redis://:$(REDIS_PASSWORD)@{{ (include "kobo.redis.fullname" .) }}-master:6379/3
            - name: CACHE_URL
              value: redis://:$(REDIS_PASSWORD)@{{ (include "kobo.redis.fullname" .) }}-master:6379/5
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "kobo.fullname" . }}-kobocat
            - configMapRef:
                name: {{ include "kobo.fullname" . }}-kobocat
          command: ["celery", "-A", "onadata", "beat", "-l", "info", "--pidfile=/tmp/celery_beat.pid", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]

      {{- with .Values.kobocat.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kobocat.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kobocat.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
