apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kobo.fullname" . }}-kobocat
  labels:
    {{- include "kobo.labels" . | nindent 4 }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ required "djangoSecret is required" .Values.kobotoolbox.djangoSecret | b64enc | quote }}
{{- range $k, $v := .Values.kobocat.env.secret }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
