apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kobo.fullname" . }}-kobocat
  labels:
    {{- include "kobo.labels" . | nindent 4 }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ required "djangoSecret is required" .Values.kobotoolbox.djangoSecret | b64enc | quote }}
  DATABASE_URL: {{ required "kobocatDatabase required" .Values.kobotoolbox.kobocatDatabase | b64enc | quote }}
  MONGO_DB_URL: {{ required "mongoDatabase required" .Values.kobotoolbox.mongoDatabase | b64enc | quote }}
  REDIS_SESSION_URL: {{ required "redisSession required" .Values.kobotoolbox.redisSession | b64enc | quote }}
  ENKETO_API_KEY: {{ required "enketoApiKey required" .Values.kobotoolbox.enketoApiKey | b64enc | quote }}
  # -- Alias for Enketo API key. Still in used but deprecated
  ENKETO_API_TOKEN: {{ required "enketoApiKey required" .Values.kobotoolbox.enketoApiKey | b64enc | quote }}
{{- range $k, $v := .Values.kobocat.env.secret }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
