apiVersion: v1
kind: Service
metadata:
  name: {{ include "kobo.fullname" . }}-kobocat
  labels:
    {{- include "kobo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kobocat.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: 8001 
      targetPort: 8000
    - name: nginx
      protocol: TCP
      port: {{ .Values.kobocat.service.port }}
      targetPort: 80
  selector:
    {{- include "kobo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kobocat