kpi:
  image:
    repository: kobotoolbox/kpi
    pullPolicy: IfNotPresent
    tag: "2.021.41"
  replicaCount: 1
  resources: {}
    # limits:
    #   cpu: 1000m
    #   memory: 1024Mi
    # requests:
    #   cpu: 100m
    #   memory: 512Mi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}
  service:
    type: ClusterIP
    port: 80
  env:
    normal: {}
    secret:
      # Overwrite these
      DATABASE_URL: "postgres://postgres:password@postgres-postgresql:5432/postgres"
      KC_DATABASE_URL: "postgres://postgres:password@postgres-postgresql:5432/kobocat"
      KPI_BROKER_URL: "redis://localhost:6379/1"
      DJANGO_SECRET_KEY: "change_me_please"
  worker:
    replicaCount: 1
    resources: {}
      # limits:
      #   cpu: 1000m
      #   memory: 1024Mi
      # requests:
      #   cpu: 100m
      #   memory: 512Mi
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80
  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local


kobocat:
  image:
    repository: kobotoolbox/kobocat
    pullPolicy: IfNotPresent
    tag: "2.021.41"
  replicaCount: 1
  resources: {}
    # limits:
    #   cpu: 1000m
    #   memory: 1024Mi
    # requests:
    #   cpu: 100m
    #   memory: 512Mi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}
  service:
    type: ClusterIP
    port: 80
  env:
    normal: {}
    secret:
      # Overwrite these
      DATABASE_URL: "postgis://postgres:password@postgres-postgresql:5432/postgres"
      DJANGO_SECRET_KEY: "change_me_too_please"
      KOBOCAT_BROKER_URL: "redis://localhost:6379/1"
  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  worker:
    replicaCount: 1
    resources: {}
      # limits:
      #   cpu: 1000m
      #   memory: 1024Mi
      # requests:
      #   cpu: 100m
      #   memory: 512Mi
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80

    

enketo:
  image:
    repository: kobotoolbox/enketo-express-extra-widgets
    pullPolicy: IfNotPresent
    tag: "2.8.1"
  replicaCount: 1
  resources: {}
    # limits:
    #   cpu: 1000m
    #   memory: 1024Mi
    # requests:
    #   cpu: 100m
    #   memory: 512Mi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
