apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kobo.fullname" . }}-enketo
  labels:
    {{- include "kobo.labels" . | nindent 4 }}
type: Opaque
data:
  ENKETO_LINKED_FORM_AND_DATA_SERVER_API_KEY: {{ required "enketoApiKey required" .Values.kobotoolbox.enketoApiKey | b64enc | quote }}
{{- range $k, $v := .Values.enketo.env.secret }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
