{{- if .Values.preInstall.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kobo.fullname" . }}-kpi
  labels:
    {{- include "kobo.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "0"
    checksum/secret: {{ include (print $.Template.BasePath "/kpi/secrets.yaml") . | sha256sum }}
    checksum/configmap: {{ include (print $.Template.BasePath "/kpi/configmap.yaml") . | sha256sum }}
    tag: "{{ .Values.kpi.image.tag }}"
spec:
  activeDeadlineSeconds: {{ default 600 .Values.preInstall.activeDeadlineSeconds }}
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install-job
        image: "{{ .Values.kpi.image.repository }}:{{ .Values.kpi.image.tag }}"
        imagePullPolicy: {{ .Values.kpi.image.pullPolicy }}
        command: ["./manage.py","migrate"]
        env:
          - name: DATABASE_URL
            value: {{ required "kpi.env.secret.DATABASE_URL is a required value." .Values.kpi.env.secret.DATABASE_URL }}
          - name: KC_DATABASE_URL
            value: {{ required "kobocatDatabase required" .Values.kobotoolbox.kobocatDatabase }}
          - name: DJANGO_SECRET_KEY
            value: {{ required "djangoSecret is a required value." .Values.kobotoolbox.djangoSecret }}
        {{- range $k, $v := .Values.kpi.env.normal }}
          - name: {{ $k }}
            value: {{ $v | quote }}
        {{- end }}
{{- end }}
