apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kobo.fullname" . }}-kpi
  labels:
    {{- include "kobo.labels" . | nindent 4 }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.kobotoolbox.djangoSecret | b64enc | quote }}
  KC_DATABASE_URL: {{ required "kobocatDatabase required" .Values.kobotoolbox.kobocatDatabase | b64enc | quote }}
  MONGO_DB_URL: {{ required "mongoDatabase required" .Values.kobotoolbox.mongoDatabase | b64enc | quote }}
  REDIS_SESSION_URL: {{ required "redisSession required" .Values.kobotoolbox.redisSession | b64enc | quote }}
{{- range $k, $v := .Values.kpi.env.secret }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}