apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kobo.fullname" . }}-kpi
  labels:
    {{- include "kobo.labels" . | nindent 4 }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.kobotoolbox.djangoSecret | b64enc | quote }}
  KPI_MONGO_PASS: {{ required "mongoPass is required" .Values.kobotoolbox.mongoPass | b64enc | quote }}
{{- range $k, $v := .Values.kpi.env.secret }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}